# Generated by Django 4.2.30 on 2026-09-20 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_age_profile_city_profile_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='questionnaire_completed',
            field=models.BooleanField(default=False),
        ),
    ]
