# Generated by Django 4.2.30 on 2026-09-20 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('display_order', 'name'),
            },
        ),
        migrations.AddField(
            model_name='question',
            name='help_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='is_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('SINGLE_CHOICE', 'Single choice'), ('MULTIPLE_CHOICE', 'Multiple choice'), ('SCALE', 'Scale'), ('YES_NO', 'Yes/No')], default='SINGLE_CHOICE', max_length=30),
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=255)),
                ('option_value', models.CharField(max_length=100)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('compatibility_value', models.FloatField(default=1.0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='questionnaire.question')),
            ],
            options={
                'ordering': ('display_order', 'id'),
            },
        ),
        migrations.AddField(
            model_name='question',
            name='category_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='questionnaire.questionnairecategory'),
        ),
        migrations.AddField(
            model_name='questionresponse',
            name='selected_options',
            field=models.ManyToManyField(blank=True, related_name='responses', to='questionnaire.questionoption'),
        ),
        migrations.AddConstraint(
            model_name='questionoption',
            constraint=models.UniqueConstraint(fields=('question', 'option_value'), name='unique_question_option_value'),
        ),
    ]
