# Generated by Django 5.2.6 on 2026-09-29 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0004_questionresponse_other_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionresponse',
            name='importance',
            field=models.CharField(choices=[('MOST_IMPORTANT', 'Most Important'), ('NEUTRAL', 'Neutral'), ('NOT_VERY_IMPORTANT', 'Not Very Important')], default='NEUTRAL', max_length=24),
        ),
    ]
