# Generated by Django 5.2.6 on 2026-10-01 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0005_questionresponse_importance'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='questionnaire/questions/'),
        ),
        migrations.AddField(
            model_name='question',
            name='image_alt_text',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
